// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzwycmtoqengsmqffcus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6d3ljbXRvcWVuZ3NtcWZmY3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTE0NDUsImV4cCI6MjA2NDU4NzQ0NX0.q0fAyKJLhn-zdnvhHrFVDTaf-oEqGhSavRQV8myC3O4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);